import { useRef, useState } from 'react'
import {
  Bot,
  Brain,
  ChevronRight,
  Clock,
  Hash,
  Loader2,
  RefreshCw,
  Search,
  Send,
  Shield,
  Tag,
  User,
} from 'lucide-react'
import { Badge } from '@/components/ui/badge'
import { Button } from '@/components/ui/button'
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card'
import { Input } from '@/components/ui/input'
import { Skeleton } from '@/components/ui/skeleton'
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs'
import {
  useCaseSummary,
  useChatHistory,
  useEntities,
  useKeywords,
  useProcessingStatus,
  useRegenerateCaseSummary,
  useSendChatMessage,
  useTimeline,
} from '@/hooks/use-ai'
import type { AiChatMessage, EvidenceEntity, EntityType } from '@/types/ai'

// ── Helpers ───────────────────────────────────────────────────────────────────

const ENTITY_TYPE_COLORS: Record<EntityType, string> = {
  person: 'bg-blue-100 text-blue-800',
  email: 'bg-green-100 text-green-800',
  phone: 'bg-teal-100 text-teal-800',
  organization: 'bg-purple-100 text-purple-800',
  domain: 'bg-orange-100 text-orange-800',
  url: 'bg-orange-100 text-orange-800',
  ip_address: 'bg-red-100 text-red-800',
  date: 'bg-slate-100 text-slate-800',
  location: 'bg-emerald-100 text-emerald-800',
  country: 'bg-emerald-100 text-emerald-800',
  city: 'bg-emerald-100 text-emerald-800',
  device: 'bg-indigo-100 text-indigo-800',
  os: 'bg-indigo-100 text-indigo-800',
  browser: 'bg-indigo-100 text-indigo-800',
  filename: 'bg-yellow-100 text-yellow-800',
  file_hash: 'bg-yellow-100 text-yellow-800',
  bank_account: 'bg-pink-100 text-pink-800',
  crypto_wallet: 'bg-pink-100 text-pink-800',
  vehicle_number: 'bg-cyan-100 text-cyan-800',
  unknown: 'bg-slate-100 text-slate-600',
}

function fmt(d: string | null | undefined) {
  if (!d) return '—'
  return new Date(d).toLocaleString('en-US', {
    month: 'short',
    day: 'numeric',
    year: 'numeric',
    hour: '2-digit',
    minute: '2-digit',
  })
}

// ── AI Summary Panel ──────────────────────────────────────────────────────────

function SummaryPanel({ caseId }: { caseId: string }) {
  const { data: summary, isLoading } = useCaseSummary(caseId)
  const { mutate: regen, isPending: regenerating } = useRegenerateCaseSummary(caseId)

  if (isLoading) {
    return (
      <div className="space-y-3">
        <Skeleton className="h-5 w-48" />
        <Skeleton className="h-24" />
        <Skeleton className="h-4 w-3/4" />
      </div>
    )
  }

  return (
    <div className="space-y-4">
      <div className="flex items-center justify-between">
        <h3 className="flex items-center gap-2 text-sm font-semibold">
          <Brain className="h-4 w-4 text-purple-500" />
          AI Case Summary
        </h3>
        <Button
          size="sm"
          variant="outline"
          onClick={() => regen()}
          disabled={regenerating}
        >
          {regenerating ? (
            <Loader2 className="mr-1.5 h-3.5 w-3.5 animate-spin" />
          ) : (
            <RefreshCw className="mr-1.5 h-3.5 w-3.5" />
          )}
          {summary ? 'Regenerate' : 'Generate'}
        </Button>
      </div>

      {!summary ? (
        <div className="rounded-lg border border-dashed p-8 text-center">
          <Brain className="mx-auto mb-2 h-8 w-8 text-muted-foreground/40" />
          <p className="text-sm text-muted-foreground">
            No summary generated yet. Click "Generate" to create an AI summary of this case.
          </p>
          <p className="mt-1 text-xs text-muted-foreground">
            Requires at least one processed evidence item.
          </p>
        </div>
      ) : (
        <div className="space-y-4">
          <Card>
            <CardContent className="pt-4 pb-4">
              <p className="text-sm leading-relaxed">{summary.summaryText}</p>
              {summary.modelUsed && (
                <p className="mt-2 text-xs text-muted-foreground">
                  Generated by {summary.modelUsed} · {fmt(summary.updatedAt)}
                </p>
              )}
            </CardContent>
          </Card>

          {summary.keyFindings.length > 0 && (
            <div className="space-y-2">
              <h4 className="text-xs font-semibold uppercase tracking-wider text-muted-foreground">
                Key Findings
              </h4>
              <ul className="space-y-1">
                {summary.keyFindings.map((f, i) => (
                  <li key={i} className="flex items-start gap-2 text-sm">
                    <ChevronRight className="mt-0.5 h-3.5 w-3.5 shrink-0 text-primary" />
                    {f}
                  </li>
                ))}
              </ul>
            </div>
          )}

          {summary.potentialLeads.length > 0 && (
            <div className="space-y-2">
              <h4 className="text-xs font-semibold uppercase tracking-wider text-muted-foreground">
                Potential Leads
              </h4>
              <ul className="space-y-1">
                {summary.potentialLeads.map((l, i) => (
                  <li key={i} className="flex items-start gap-2 text-sm">
                    <Search className="mt-0.5 h-3.5 w-3.5 shrink-0 text-amber-500" />
                    {l}
                  </li>
                ))}
              </ul>
            </div>
          )}

          {summary.openQuestions.length > 0 && (
            <div className="space-y-2">
              <h4 className="text-xs font-semibold uppercase tracking-wider text-muted-foreground">
                Open Questions
              </h4>
              <ul className="space-y-1">
                {summary.openQuestions.map((q, i) => (
                  <li key={i} className="flex items-start gap-2 text-sm text-muted-foreground">
                    <span className="shrink-0 font-bold">Q:</span>
                    {q}
                  </li>
                ))}
              </ul>
            </div>
          )}
        </div>
      )}
    </div>
  )
}

// ── Entities Panel ────────────────────────────────────────────────────────────

const ENTITY_TYPES: { value: string; label: string }[] = [
  { value: '', label: 'All' },
  { value: 'person', label: 'People' },
  { value: 'email', label: 'Email' },
  { value: 'phone', label: 'Phone' },
  { value: 'ip_address', label: 'IP Address' },
  { value: 'domain', label: 'Domain' },
  { value: 'url', label: 'URL' },
  { value: 'organization', label: 'Org' },
  { value: 'crypto_wallet', label: 'Crypto' },
  { value: 'file_hash', label: 'Hash' },
  { value: 'location', label: 'Location' },
]

function EntityBadge({ entity }: { entity: EvidenceEntity }) {
  const color = ENTITY_TYPE_COLORS[entity.entityType] ?? 'bg-slate-100 text-slate-800'
  return (
    <div className="flex items-start gap-2 rounded-md border bg-card p-2.5">
      <span className={`shrink-0 rounded px-1.5 py-0.5 text-xs font-medium ${color}`}>
        {entity.entityType.replace('_', ' ')}
      </span>
      <div className="min-w-0 flex-1">
        <p className="truncate text-sm font-mono">{entity.value}</p>
        {entity.context && (
          <p className="mt-0.5 line-clamp-1 text-xs text-muted-foreground">{entity.context}</p>
        )}
      </div>
      <span className="shrink-0 text-xs text-muted-foreground">
        {Math.round(entity.confidence * 100)}%
      </span>
    </div>
  )
}

function EntitiesPanel({ caseId }: { caseId: string }) {
  const [entityType, setEntityType] = useState('')
  const [search, setSearch] = useState('')
  const { data, isLoading } = useEntities(caseId, {
    entityType: entityType || undefined,
    q: search || undefined,
    pageSize: 100,
  })

  return (
    <div className="space-y-4">
      <div className="flex flex-wrap items-center gap-2">
        <div className="relative flex-1 min-w-[180px]">
          <Search className="absolute left-2.5 top-2.5 h-3.5 w-3.5 text-muted-foreground" />
          <Input
            className="pl-8 h-8 text-sm"
            placeholder="Search entities…"
            value={search}
            onChange={(e) => setSearch(e.target.value)}
          />
        </div>
        <div className="flex flex-wrap gap-1">
          {ENTITY_TYPES.map((t) => (
            <button
              key={t.value}
              onClick={() => setEntityType(t.value)}
              className={`rounded-full border px-2.5 py-0.5 text-xs transition-colors ${
                entityType === t.value
                  ? 'bg-primary text-primary-foreground border-primary'
                  : 'border-border hover:border-primary/40'
              }`}
            >
              {t.label}
            </button>
          ))}
        </div>
      </div>

      {isLoading ? (
        <div className="space-y-2">
          {Array.from({ length: 6 }).map((_, i) => (
            <Skeleton key={i} className="h-10" />
          ))}
        </div>
      ) : !data || data.items.length === 0 ? (
        <div className="rounded-lg border border-dashed p-8 text-center text-sm text-muted-foreground">
          No entities extracted yet. Evidence must be fully processed.
        </div>
      ) : (
        <div className="space-y-1.5">
          <p className="text-xs text-muted-foreground">
            {data.total} entities{entityType ? ` of type "${entityType}"` : ''}
          </p>
          {data.items.map((e) => (
            <EntityBadge key={e.id} entity={e} />
          ))}
          {data.total > data.items.length && (
            <p className="text-center text-xs text-muted-foreground pt-2">
              Showing {data.items.length} of {data.total}
            </p>
          )}
        </div>
      )}
    </div>
  )
}

// ── Keywords Panel ────────────────────────────────────────────────────────────

function KeywordsPanel({ caseId }: { caseId: string }) {
  const { data, isLoading } = useKeywords(caseId, { pageSize: 50 })

  if (isLoading) {
    return <Skeleton className="h-40" />
  }

  if (!data || data.items.length === 0) {
    return (
      <div className="rounded-lg border border-dashed p-8 text-center text-sm text-muted-foreground">
        No keywords extracted yet.
      </div>
    )
  }

  const maxScore = Math.max(...data.items.map((k) => k.score))

  return (
    <div className="space-y-3">
      <p className="text-xs text-muted-foreground">{data.total} keywords across all evidence</p>
      <div className="flex flex-wrap gap-2">
        {data.items.map((kw) => {
          const rel = maxScore > 0 ? kw.score / maxScore : 0
          const size =
            rel > 0.8 ? 'text-base font-semibold' : rel > 0.5 ? 'text-sm font-medium' : 'text-xs'
          return (
            <Badge
              key={kw.id}
              variant="secondary"
              className={`${size} cursor-default`}
              title={`Score: ${kw.score.toFixed(3)}`}
            >
              <Hash className="mr-0.5 h-3 w-3 opacity-50" />
              {kw.keyword}
            </Badge>
          )
        })}
      </div>
    </div>
  )
}

// ── Timeline Panel ────────────────────────────────────────────────────────────

function TimelinePanel({ caseId }: { caseId: string }) {
  const { data, isLoading } = useTimeline(caseId, { pageSize: 100 })

  if (isLoading) {
    return (
      <div className="space-y-2">
        {Array.from({ length: 5 }).map((_, i) => (
          <Skeleton key={i} className="h-14" />
        ))}
      </div>
    )
  }

  if (!data || data.items.length === 0) {
    return (
      <div className="rounded-lg border border-dashed p-8 text-center text-sm text-muted-foreground">
        No timeline events detected yet.
      </div>
    )
  }

  return (
    <div className="space-y-3">
      <p className="text-xs text-muted-foreground">{data.total} events extracted</p>
      <div className="space-y-2">
        {data.items.map((ev) => (
          <div key={ev.id} className="flex items-start gap-3 rounded-md border bg-card p-3">
            <div className="flex h-7 w-7 shrink-0 items-center justify-center rounded-full bg-primary/10">
              <Clock className="h-3.5 w-3.5 text-primary" />
            </div>
            <div className="flex-1 min-w-0">
              <div className="flex items-center gap-2 flex-wrap">
                <span className="text-sm font-medium">{ev.eventTitle}</span>
                <Badge variant="outline" className="text-xs">
                  {ev.eventType.replace(/_/g, ' ')}
                </Badge>
              </div>
              {ev.description && (
                <p className="mt-0.5 text-xs text-muted-foreground line-clamp-1">
                  {ev.description}
                </p>
              )}
              {ev.eventTimestamp && (
                <p className="mt-0.5 text-xs text-muted-foreground">
                  {fmt(ev.eventTimestamp)}
                </p>
              )}
            </div>
            <span className="shrink-0 text-xs text-muted-foreground">
              {Math.round(ev.confidence * 100)}%
            </span>
          </div>
        ))}
      </div>
    </div>
  )
}

// ── Processing Status ─────────────────────────────────────────────────────────

function ProcessingStatusPanel({ caseId }: { caseId: string }) {
  const { data, isLoading } = useProcessingStatus(caseId)

  if (isLoading) {
    return <Skeleton className="h-32" />
  }

  if (!data || data.length === 0) {
    return (
      <div className="rounded-lg border border-dashed p-6 text-center text-sm text-muted-foreground">
        No evidence uploaded yet.
      </div>
    )
  }

  const STATUS_COLOR: Record<string, string> = {
    completed: 'text-green-600',
    failed: 'text-red-600',
    processing: 'text-blue-600',
    queued: 'text-amber-600',
  }

  function statusColor(s: string) {
    if (s === 'completed') return STATUS_COLOR.completed
    if (s === 'failed') return STATUS_COLOR.failed
    if (s.includes('queue') || s === 'uploaded') return STATUS_COLOR.queued
    return STATUS_COLOR.processing
  }

  return (
    <div className="space-y-2">
      {data.map((item) => (
        <div
          key={item.evidenceId}
          className="flex items-center gap-3 rounded-md border bg-card px-3 py-2"
        >
          <div className="min-w-0 flex-1">
            <p className="truncate text-sm font-medium">{item.filename}</p>
            <div className="mt-0.5 flex items-center gap-3 text-xs text-muted-foreground">
              <span className={`font-medium ${statusColor(item.status)}`}>
                {item.status.replace(/_/g, ' ')}
              </span>
              {item.language && <span>Lang: {item.language}</span>}
              {item.wordCount != null && <span>{item.wordCount.toLocaleString()} words</span>}
            </div>
          </div>
          <div className="flex shrink-0 items-center gap-3 text-xs text-muted-foreground">
            <span title="Entities">{item.entityCount} entities</span>
            <span title="Keywords">{item.keywordCount} kw</span>
            <span title="Timeline events">{item.timelineEventCount} events</span>
            {item.hasSummary && (
              <span title="Has AI summary">
                <Shield className="h-3.5 w-3.5 text-green-500" />
              </span>
            )}
          </div>
        </div>
      ))}
    </div>
  )
}

// ── Chat Panel ────────────────────────────────────────────────────────────────

function ChatBubble({ msg }: { msg: AiChatMessage }) {
  const isUser = msg.role === 'user'
  return (
    <div className={`flex gap-2.5 ${isUser ? 'flex-row-reverse' : ''}`}>
      <div
        className={`flex h-7 w-7 shrink-0 items-center justify-center rounded-full ${
          isUser ? 'bg-primary text-primary-foreground' : 'bg-purple-100 text-purple-700'
        }`}
      >
        {isUser ? <User className="h-3.5 w-3.5" /> : <Bot className="h-3.5 w-3.5" />}
      </div>
      <div
        className={`max-w-[80%] rounded-lg px-3 py-2 text-sm ${
          isUser
            ? 'bg-primary text-primary-foreground rounded-tr-none'
            : 'bg-muted rounded-tl-none'
        }`}
      >
        <p className="whitespace-pre-wrap leading-relaxed">{msg.content}</p>
        {msg.evidenceReferences.length > 0 && (
          <div className="mt-1 flex flex-wrap gap-1">
            {msg.evidenceReferences.map((ref) => (
              <span
                key={ref}
                title={ref}
                className="max-w-[220px] truncate rounded bg-black/10 px-1.5 py-0.5 text-xs font-mono"
              >
                Evidence: {ref}
              </span>
            ))}
          </div>
        )}
        <p className={`mt-1 text-xs opacity-60 ${isUser ? 'text-right' : ''}`}>
          {new Date(msg.createdAt).toLocaleTimeString('en-US', {
            hour: '2-digit',
            minute: '2-digit',
          })}
        </p>
      </div>
    </div>
  )
}

function ChatPanel({ caseId }: { caseId: string }) {
  const [input, setInput] = useState('')
  const endRef = useRef<HTMLDivElement>(null)
  const { data: history, isLoading: historyLoading } = useChatHistory(caseId)
  const { mutate: send, isPending: sending } = useSendChatMessage(caseId)

  function handleSend() {
    const msg = input.trim()
    if (!msg || sending) return
    setInput('')
    send(msg, {
      onSuccess: () => {
        setTimeout(() => endRef.current?.scrollIntoView({ behavior: 'smooth' }), 50)
      },
    })
  }

  function handleKey(e: React.KeyboardEvent<HTMLInputElement>) {
    if (e.key === 'Enter' && !e.shiftKey) {
      e.preventDefault()
      handleSend()
    }
  }

  const messages = history?.items ?? []

  return (
    <div className="flex flex-col gap-3" style={{ minHeight: '400px' }}>
      {/* AI disclaimer */}
      <div className="flex items-start gap-2 rounded-lg bg-amber-50 border border-amber-200 px-3 py-2 text-xs text-amber-800">
        <Shield className="mt-0.5 h-3.5 w-3.5 shrink-0" />
        <span>
          AI assistant is case-scoped and only references uploaded evidence.
          It will say "I don't know" when evidence is insufficient and never makes investigative decisions.
        </span>
      </div>

      {/* Message list */}
      <div className="flex-1 overflow-y-auto space-y-3 rounded-lg border bg-background p-3 min-h-[280px] max-h-[400px]">
        {historyLoading ? (
          <div className="flex items-center justify-center h-full text-sm text-muted-foreground">
            <Loader2 className="mr-2 h-4 w-4 animate-spin" />
            Loading conversation…
          </div>
        ) : messages.length === 0 ? (
          <div className="flex flex-col items-center justify-center h-full gap-2 text-muted-foreground">
            <Bot className="h-8 w-8 opacity-30" />
            <p className="text-sm">Ask the AI about this case</p>
            <div className="flex flex-wrap justify-center gap-1.5 max-w-xs">
              {[
                'Summarize all evidence',
                'List all email addresses found',
                'What are the key findings?',
              ].map((prompt) => (
                <button
                  key={prompt}
                  onClick={() => setInput(prompt)}
                  className="rounded-full border px-2.5 py-1 text-xs hover:border-primary/50 transition-colors"
                >
                  {prompt}
                </button>
              ))}
            </div>
          </div>
        ) : (
          messages.map((m) => <ChatBubble key={m.id} msg={m} />)
        )}
        <div ref={endRef} />
      </div>

      {/* Input */}
      <div className="flex items-center gap-2">
        <Input
          className="flex-1"
          placeholder="Ask about this case's evidence…"
          value={input}
          onChange={(e) => setInput(e.target.value)}
          onKeyDown={handleKey}
          disabled={sending}
          maxLength={4000}
        />
        <Button
          size="icon"
          onClick={handleSend}
          disabled={!input.trim() || sending}
        >
          {sending ? (
            <Loader2 className="h-4 w-4 animate-spin" />
          ) : (
            <Send className="h-4 w-4" />
          )}
        </Button>
      </div>
      <p className="text-xs text-muted-foreground text-right">
        {input.length}/4000
      </p>
    </div>
  )
}

// ── AI Tab (main export) ──────────────────────────────────────────────────────

export function AiTab({ caseId }: { caseId: string }) {
  return (
    <div className="space-y-6">
      <Tabs defaultValue="summary">
        <TabsList className="flex-wrap">
          <TabsTrigger value="summary">
            <Brain className="mr-1.5 h-3.5 w-3.5" />
            Summary
          </TabsTrigger>
          <TabsTrigger value="entities">
            <Tag className="mr-1.5 h-3.5 w-3.5" />
            Entities
          </TabsTrigger>
          <TabsTrigger value="keywords">
            <Hash className="mr-1.5 h-3.5 w-3.5" />
            Keywords
          </TabsTrigger>
          <TabsTrigger value="timeline">
            <Clock className="mr-1.5 h-3.5 w-3.5" />
            Timeline
          </TabsTrigger>
          <TabsTrigger value="chat">
            <Bot className="mr-1.5 h-3.5 w-3.5" />
            Chat
          </TabsTrigger>
          <TabsTrigger value="status">
            <Shield className="mr-1.5 h-3.5 w-3.5" />
            Processing
          </TabsTrigger>
        </TabsList>

        <TabsContent value="summary" className="mt-4">
          <SummaryPanel caseId={caseId} />
        </TabsContent>

        <TabsContent value="entities" className="mt-4">
          <EntitiesPanel caseId={caseId} />
        </TabsContent>

        <TabsContent value="keywords" className="mt-4">
          <Card>
            <CardHeader className="pb-2">
              <CardTitle className="text-sm">Extracted Keywords</CardTitle>
            </CardHeader>
            <CardContent>
              <KeywordsPanel caseId={caseId} />
            </CardContent>
          </Card>
        </TabsContent>

        <TabsContent value="timeline" className="mt-4">
          <TimelinePanel caseId={caseId} />
        </TabsContent>

        <TabsContent value="chat" className="mt-4">
          <ChatPanel caseId={caseId} />
        </TabsContent>

        <TabsContent value="status" className="mt-4">
          <Card>
            <CardHeader className="pb-2">
              <CardTitle className="text-sm">Evidence Processing Status</CardTitle>
            </CardHeader>
            <CardContent>
              <ProcessingStatusPanel caseId={caseId} />
            </CardContent>
          </Card>
        </TabsContent>
      </Tabs>
    </div>
  )
}
